export const businessCategories = [
    "Accounting",
    "Addiction Treatment",
    "Agriculture",
    "Aerobics",
    "Aerospace",
    "Appliances",
    "Art",
    "Athletics",
    "Audio",
    "Audio Content",
    "Automobiles",
    "Aviation",
    "Babies",
    "Bands",
    "Banking",
    "Baseball",
    "Basketball",
    "Baptist",
    "Beauty",
    "Bedding",
    "Bicycles",
    "Biotechnology",
    "Bitcoin",
    "Blockchain",
    "Books",
    "Broadcasting",
    "Building",
    "Business",
    "Cable",
    "Cafe",
    "Camping",
    "Car",
    "Carpet",
    "Cars",
    "Catholic",
    "Cell Phones",
    "Charity",
    "Chemical",
    "Children",
    "Church",
    "City Department",
    "Clean Energy",
    "Clothing",
    "CMS",
    "College",
    "Communication",
    "Community",
    "Community College",
    "Community Living",
    "Computers",
    "Construction",
    "Cooking",
    "Corporate",
    "Coworking Space",
    "CRM",
    "Dance",
    "Data",
    "Database",
    "Dating Services",
    "Delivery",
    "Dentist",
    "Design",
    "Disability Services",
    "Digital Communications",
    "Digital Education",
    "Digital Library",
    "Digital Marketing",
    "Distribution Service",
    "Diversity",
    "Economics",
    "E-Commerce",
    "Education",
    "Electronics",
    "Emergency Services",
    "Energy",
    "Engineering",
    "English",
    "Entertainment",
    "Environment",
    "Ethereum",
    "Estates",
    "Equipment",
    "Events",
    "Executive Teams",
    "Faculty",
    "Family",
    "Farming",
    "Fashion",
    "Fintech",
    "Fitness",
    "Food",
    "Food Delivery",
    "Football",
    "Furniture",
    "Games",
    "Gaming",
    "Generative AI",
    "Generative Pre Trained Transformers",
    "Gospel",
    "Government",
    "Graduate School",
    "Green Energy",
    "Groceries",
    "Hair",
    "Hardware",
    "Health",
    "Health Care",
    "Health Care Billing",
    "Health Care Services",
    "Health Insurance",
    "Hospitals",
    "Hospital Equipment",
    "Hospitality",
    "Housing",
    "Human Resources",
    "Information",
    "Internet",
    "Instrumentation",
    "Investment Banking",
    "Investment Company",
    "Investment Management",
    "Investment Planning",
    "Jehovah’s Witness Kingdom Hall",
    "Jesus Disciple",
    "Jewish",
    "Jewish Ministries",
    "Judicial",
    "Justice",
    "Kids",
    "Kiosk",
    "Laboratory",
    "Land",
    "Large Language Models",
    "Law",
    "Live Events",
    "LLM",
    "Lodging",
    "Luggage",
    "Machine Learning",
    "Machinery",
    "Machine Repair",
    "Maintenance",
    "Mainstream Media",
    "Management",
    "Maternity",
    "Meal",
    "Media",
    "Medical",
    "Medical Education",
    "Medical Equipment",
    "Men",
    "Mens Clothing",
    "Mental Health",
    "Metal",
    "Mining",
    "Mission",
    "Mobile",
    "Modeling",
    "Motion Picture",
    "Municipal",
    "Music",
    "National Forest",
    "National Park",
    "Neurologist",
    "Neurology",
    "News",
    "NewsLetter",
    "NFTS",
    "Nursing",
    "Nursing Home",
    "Nutrition",
    "Non-denominational Church",
    "Non-profit Organization",
    "Notary Public",
    "Nuclear",
    "Organization",
    "Organizations",
    "Organizing",
    "Occupational Health",
    "Office",
    "Oil",
    "Organic Food",
    "Packaging",
    "Pain Control",
    "Parking",
    "Patients",
    "Patient Care",
    "Patient Education",
    "Patient Services",
    "Payroll",
    "Pharmacy",
    "Psychology",
    "Physical Health",
    "Photos",
    "Photography",
    "Pregnancy",
    "Private College",
    "Private Equity",
    "Private Sector",
    "Public Health",
    "Public Sector",
    "Research",
    "Residential",
    "SAAS",
    "SAAS Management",
    "SAAS Savings",
    "SAAS Marketing",
    "SAAS Research",
    "Savings",
    "School",
    "Science",
    "Security",
    "Seventh Day Adventist",
    "Skateboarding",
    "Social Media",
    "Social Media",
    "Software Engineering",
    "Software Security",
    "Startups",
    "Technical Services",
    "Technology",
    "Telecommunications",
    "Tik Tok",
    "University",
    "Used Goods",
    "Ventures",
    "Venture Capital",
    "Venture Studio",
    "Video Games",
    "Volunteering",
    "Other",
];