export const businessCategories = [
    "Accounting",
    "Addiction Treatment",
    "Agriculture",
    "Aerobics",
    "Aerospace",
    "Appliances",
    "Art",
    "Athletics",
    "Audio Content",
    "Automobiles",
    "Aviation",
    "Babies",
    "Bands",
    "Banking",
    "Baseball",
    "Basketball",
    "Beauty",
    "Bedding",
    "Bicycles",
    "Biotechnology",
    "Blockchain",
    "Books",
    "Broadcasting",
    "Building",
    "Business",
    "Cable",
    "Cafe",
    "Camping",
    "Car",
    "Carpet",
    "Cars",
    "Cell Phones",
    "Charity",
    "Chemical",
    "Children",
    "Church",
    "City Department",
    "Clean Energy",
    "Clothing",
    "CMS",
    "College",
    "Communication",
    "Community",
    "Community College",
    "Community Living",
    "Computers",
    "Construction",
    "Cooking",
    "Corporate",
    "Coworking Space",
    "CRM",
    "Dance",
    "Data",
    "Database",
    "Dentist",
    "Design",
    "Disability Services",
    "Digital Communications",
    "Digital Education",
    "Digital Library",
    "Digital Marketing",
    "Distribution Service",
    "Diversity",
    "Economics",
    "E-Commerce",
    "Education",
    "Electronics",
    "Emergency Services",
    "Energy",
];